###############################################################################
# Makefile for the project beam_ctrl
###############################################################################

## General Flags

## Build
all: 

## Document target
##	pwd
	doxygen tsr_doxy.proj

## Other dependencies

